/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Famacy;
import Famacy.model.Employee;
import Famacy.view.MedicineManagementForm;
import Famacy.view.ConsumableManagementForm;
import Famacy.view.EmployeeManagementForm;
import Famacy.view.TransactionManagementForm;
import Famacy.view.ChangePasswordForm;
import Famacy.view.DeleteAccountForm;
import Famacy.view.RegistrationForm;
import Famacy.view.ResetPasswordForm;
import Famacy.view.MessageForm;
import Famacy.view.LoginForm;
import Famacy.view.ChangeRoleForm;

import javax.swing.*;
import java.awt.*;

import Famacy.service.AccountService;
import Famacy.service.EmployeeService;
import Famacy.service.MedicineService;
import Famacy.service.ConsumableService;
import Famacy.service.TransactionService;


/**
 *
 * @author ADMIN
 */
public class PharmacyMain extends javax.swing.JFrame {
    private String username;
    private String role;
    private EmployeeService employeeService;
    private MedicineService medicineService;
    private ConsumableService consumableService;
    private TransactionService transactionService;
    private AccountService accountService;
    private MedicineManagementForm medicineForm;
    private EmployeeManagementForm employeeForm;
    private ConsumableManagementForm consumableForm;
        //getContentPane().setBackground(Color.RED);
    /**
     * Creates new form FamacyMain_JFrame
     * @param username
     */
    public PharmacyMain(String username) {
        this.username = username;
        this.accountService = new AccountService();
        this.role = accountService.getRoleByUsername(username);
        this.employeeService = new EmployeeService();
        this.medicineService = new MedicineService();
        this.consumableService = new ConsumableService();
        this.transactionService = new TransactionService();
        employeeForm = new EmployeeManagementForm(employeeService);
        medicineForm = new MedicineManagementForm(medicineService);
        consumableForm = new ConsumableManagementForm(consumableService);
        initComponents();
        checkRole();
        setResizable(false);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        popupMenu = new javax.swing.JPopupMenu();
        personalInforMI = new javax.swing.JMenuItem();
        yourAccountMI = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        medicineButton = new javax.swing.JButton();
        consumableButton = new javax.swing.JButton();
        chatButton = new javax.swing.JButton();
        transactionButton = new javax.swing.JButton();
        manageAccountButton = new javax.swing.JButton();
        manageEmployeeButton = new javax.swing.JButton();
        popupButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        userRoleInfoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userInfoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        personalInforMI.setBackground(new java.awt.Color(204, 204, 204));
        personalInforMI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        personalInforMI.setText("Personal Info");
        personalInforMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalInforMIActionPerformed(evt);
            }
        });
        popupMenu.add(personalInforMI);

        yourAccountMI.setBackground(new java.awt.Color(204, 204, 204));
        yourAccountMI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        yourAccountMI.setText("Your Account");
        yourAccountMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourAccountMIActionPerformed(evt);
            }
        });
        popupMenu.add(yourAccountMI);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Famacy Manager");
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        medicineButton.setText("Medicine");
        medicineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 324;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 11);
        jPanel1.add(medicineButton, gridBagConstraints);

        consumableButton.setText("Consumable");
        consumableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 307;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 11);
        jPanel1.add(consumableButton, gridBagConstraints);

        chatButton.setText("Internal Chat");
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 306;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 11);
        jPanel1.add(chatButton, gridBagConstraints);

        transactionButton.setText("Transation");
        transactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 318;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 6, 11);
        jPanel1.add(transactionButton, gridBagConstraints);

        manageAccountButton.setText("Manage Account");
        manageAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        jPanel1.add(manageAccountButton, gridBagConstraints);

        manageEmployeeButton.setText("Manage Employee");
        manageEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 28, 0, 11);
        jPanel1.add(manageEmployeeButton, gridBagConstraints);

        popupButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        popupButton.setText("=");
        popupButton.setComponentPopupMenu(popupMenu);
        popupButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        popupButton.setRolloverEnabled(false);
        popupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupButtonActionPerformed(evt);
            }
        });

        userRoleInfoLabel.setText("jLabel4");

        jLabel3.setText("| Role:");

        userInfoLabel.setText("jLabel2");

        jLabel1.setText("User: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userRoleInfoLabel)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(userInfoLabel)
                .addComponent(jLabel3)
                .addComponent(userRoleInfoLabel))
        );

        jLabel5.setFont(new java.awt.Font("Impact", 1, 70)); // NOI18N
        jLabel5.setText("Famacy");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Internal Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(436, 436, 436)
                .addComponent(popupButton)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(431, 431, 431))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(482, 482, 482))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(popupButton)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manageAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountButtonActionPerformed
        showManageAccountDialog();
    }//GEN-LAST:event_manageAccountButtonActionPerformed

    private void manageEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeButtonActionPerformed
        // TODO add your handling code here:
        
        employeeForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        employeeForm.setVisible(true);
    }//GEN-LAST:event_manageEmployeeButtonActionPerformed

    private void popupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupButtonActionPerformed
        // TODO add your handling code here:
        if (popupButton.isSelected()) {
            popupButton.setForeground(Color.WHITE);
            popupMenu.show(popupButton, -65, 45);
        } 
        popupButton.setForeground(Color.BLACK);

    }//GEN-LAST:event_popupButtonActionPerformed

    private void medicineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineButtonActionPerformed
        // TODO add your handling code here:
        
        medicineForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        medicineForm.setVisible(true);
    }//GEN-LAST:event_medicineButtonActionPerformed

    private void consumableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableButtonActionPerformed
        // TODO add your handling code here:
        consumableForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        consumableForm.setVisible(true);
    }//GEN-LAST:event_consumableButtonActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
        // TODO add your handling code here:
        MessageForm chatApplicationUI = new MessageForm(username);
        chatApplicationUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        chatApplicationUI.setVisible(true);
    }//GEN-LAST:event_chatButtonActionPerformed

    private void transactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionButtonActionPerformed
        // TODO add your handling code here:
        TransactionManagementForm transactionForm = new TransactionManagementForm(transactionService);
        transactionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        transactionForm.setVisible(true);
    }//GEN-LAST:event_transactionButtonActionPerformed

    private void yourAccountMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourAccountMIActionPerformed
        // TODO add your handling code here:
        showYourAccount();
        resetPopupButton();
    }//GEN-LAST:event_yourAccountMIActionPerformed

    private void personalInforMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalInforMIActionPerformed
        // TODO add your handling code here:
        showPersonalInfoDialog();
        resetPopupButton();
    }//GEN-LAST:event_personalInforMIActionPerformed

    private void resetPopupButton() {
        popupButton.setSelected(false);
        popupButton.setForeground(Color.BLACK);
    }
    
    private void showYourAccount(){
        JFrame accountFrame = new JFrame("Your Account");
        accountFrame.setSize(300, 200);
        accountFrame.setLocationRelativeTo(null);
        accountFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        accountFrame.setResizable(false);

        JPanel accountPanel = new JPanel(new GridLayout(2, 1, 10, 10));
        JButton changePasswordButton = new JButton("Change Password");
        JButton logoutButton = new JButton("Logout");

        changePasswordButton.addActionListener(event -> {
            ChangePasswordForm changePasswordForm = new ChangePasswordForm(username);
            changePasswordForm.setVisible(true);
            accountFrame.dispose();
        });

        logoutButton.addActionListener(event -> {
            accountFrame.dispose();
            dispose();
            new LoginForm().setVisible(true);
        });

        accountPanel.add(changePasswordButton);
        accountPanel.add(logoutButton);
        accountFrame.add(accountPanel);
        accountFrame.setVisible(true);
    }
    
    private void checkRole() {
        if(!"admin".equals(role)){
            manageAccountButton.setVisible(false);
            manageEmployeeButton.setVisible(false);
        }
        
        if("user".equals(role)){      
            medicineForm.disableAddEditDelete();
            consumableForm.disableAddEditDelete();
        }
        
       
        userInfoLabel.setText(username);
        userRoleInfoLabel.setText(role);
    }
    
    private void showManageAccountDialog() {
        // Create a JPanel
        JPanel panel = new JPanel();
        int hgap = 20;
        int vgap = 10;
        // Set layout manager for the panel
        panel.setLayout(new GridLayout(5, 1, hgap, vgap));

        // Create buttons
        JButton createAccountButton = new JButton("Create Account");
        JButton resetPasswordButton = new JButton("Reset Password");
        JButton deleteAccountButton = new JButton("Delete Account");
        JButton changeRoleButton = new JButton("Change Role");
        JButton cancelButton = new JButton("Cancel");

        Font largeFont = new Font("Segoe UI", Font.PLAIN, 16); // Adjust the font size as needed

        // Set the larger font for each button
        createAccountButton.setFont(largeFont);
        resetPasswordButton.setFont(largeFont);
        deleteAccountButton.setFont(largeFont);
        changeRoleButton.setFont(largeFont);
        cancelButton.setFont(largeFont);

        Dimension buttonSize = new Dimension(200, 50); // Adjust the size as needed
        createAccountButton.setPreferredSize(buttonSize);
        resetPasswordButton.setPreferredSize(buttonSize);
        deleteAccountButton.setPreferredSize(buttonSize);
        changeRoleButton.setPreferredSize(buttonSize);
        cancelButton.setPreferredSize(buttonSize);

        // Add buttons to the panel
        panel.add(createAccountButton);
        panel.add(resetPasswordButton);
        panel.add(deleteAccountButton);
        panel.add(changeRoleButton);
        panel.add(cancelButton);

        // Create a JDialog
        JDialog dialog = new JDialog(this, "Manage Account", Dialog.ModalityType.MODELESS); // MODELESS to allow interaction with other buttons
        dialog.getContentPane().add(panel);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setLocationRelativeTo(this);

        // Action listeners to handle button clicks
        cancelButton.addActionListener(e -> dialog.dispose());

        createAccountButton.addActionListener(event -> {
            RegistrationForm registrationForm = new RegistrationForm(username);
            registrationForm.setVisible(true);
        });

        resetPasswordButton.addActionListener(event -> {
            ResetPasswordForm resetPasswordForm = new ResetPasswordForm(username);
            resetPasswordForm.setVisible(true);
        });

        deleteAccountButton.addActionListener(event -> {
            DeleteAccountForm deleteAccountForm = new DeleteAccountForm(username);
            deleteAccountForm.setVisible(true);
        });

        changeRoleButton.addActionListener(event -> {
            ChangeRoleForm changeRoleForm = new ChangeRoleForm(username);
            changeRoleForm.setVisible(true);
        });

        dialog.setVisible(true);
    }

    private void showPersonalInfoDialog() {
        // Create a JPanel to hold the personal info
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(6, 2, 10, 10)); // 6 rows, 2 columns, with some padding
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Add padding around the panel


        // Retrieve user data from the database (assuming the existence of a method getUserInfo)
        int EID = accountService.getEmployeeIdByUsername(username);
        Employee userInfo = employeeService.getEmployeeById(EID);

        // Add labels and fields to the panel
         // Create a larger font
        Font largerFont = new Font("Segoe UI", Font.PLAIN, 18);

        // Add labels and fields to the panel with the larger font
        JLabel idLabel = new JLabel("ID:");
        idLabel.setFont(largerFont);
        panel.add(idLabel);
        JLabel idValueLabel = new JLabel(String.valueOf(userInfo.getId()));
        idValueLabel.setFont(largerFont);
        panel.add(idValueLabel);

        JLabel nameLabel = new JLabel("Name:");
        nameLabel.setFont(largerFont);
        panel.add(nameLabel);
        JLabel nameValueLabel = new JLabel(userInfo.getName());
        nameValueLabel.setFont(largerFont);
        panel.add(nameValueLabel);

        JLabel genderLabel = new JLabel("Gender:");
        genderLabel.setFont(largerFont);
        panel.add(genderLabel);
        JLabel genderValueLabel = new JLabel(userInfo.getGender());
        genderValueLabel.setFont(largerFont);
        panel.add(genderValueLabel);

        JLabel roleLabel = new JLabel("Role:");
        roleLabel.setFont(largerFont);
        panel.add(roleLabel);
        JLabel roleValueLabel = new JLabel(userInfo.getRole());
        roleValueLabel.setFont(largerFont);
        panel.add(roleValueLabel);

        JLabel birthDayLabel = new JLabel("Birth Day:");
        birthDayLabel.setFont(largerFont);
        panel.add(birthDayLabel);
        JLabel birthDayValueLabel = new JLabel(userInfo.getBirth());
        birthDayValueLabel.setFont(largerFont);
        panel.add(birthDayValueLabel);

        JLabel phoneLabel = new JLabel("Phone:");
        phoneLabel.setFont(largerFont);
        panel.add(phoneLabel);
        JLabel phoneValueLabel = new JLabel(userInfo.getPhone());
        phoneValueLabel.setFont(largerFont);
        panel.add(phoneValueLabel);
        
        panel.setPreferredSize(new Dimension(400, 300));

        // Create a JDialog to show the panel
        JDialog dialog = new JDialog(this, "Personal Info", Dialog.ModalityType.APPLICATION_MODAL);
        dialog.getContentPane().add(panel);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setLocationRelativeTo(this);

        // Show the dialog
        dialog.setVisible(true);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chatButton;
    private javax.swing.JButton consumableButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton manageAccountButton;
    private javax.swing.JButton manageEmployeeButton;
    private javax.swing.JButton medicineButton;
    private javax.swing.JMenuItem personalInforMI;
    private javax.swing.JToggleButton popupButton;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JButton transactionButton;
    private javax.swing.JLabel userInfoLabel;
    private javax.swing.JLabel userRoleInfoLabel;
    private javax.swing.JMenuItem yourAccountMI;
    // End of variables declaration//GEN-END:variables


}
